# Create the Production Namespace (if not exist)

#kind: Namespace
#apiVersion: v1
#metadata:
#  name: production
#  labels:
#    name: production

#---

# Create a Persistent Volume mapped to a local directory
kind: PersistentVolume
apiVersion: v1
metadata:
  name: donationsdesk-pv-volume
  namespace: production
  labels:
    type: local
spec:
  storageClassName: generic
  capacity:
    storage: 5Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/kubernetes/Donations Desk"

---

# Create a Persistent Volume Claim for the pod to access the directory
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: donationsdesk-pv-claim
  namespace: production
spec:
  storageClassName: generic
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi

---

# Create the App Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: donationsdesk-deployment
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: donationsdesk
  template:
    metadata:
      labels:
        app: donationsdesk
    spec:
    # Specify the container
      containers:
        - name: donationsdesk
          image: prengineer/donationsdesk:latest
          env:
            - name: TZ
              value: America/New_York
          resources:
            limits:
              memory: "500Mi"
              cpu: "1000m"
          ports:
            - name: httpport
              containerPort: 80
          # Add the volume
          volumeMounts:
          - mountPath: "/config"
            name: donationsdesk-pv-storage
      # Specify the volume
      volumes:
      - name: donationsdesk-pv-storage
        persistentVolumeClaim:
          claimName: donationsdesk-pv-claim

---

# Create the Exposed App Service

apiVersion: v1
kind: Service
metadata:
  name: donationsdesk-external-service
  namespace: production
spec:
  selector:
    app: donationsdesk
  type: LoadBalancer
  ports:
  - name: httpport
    protocol: TCP
    port: 8003
    targetPort: 80
status:
  loadBalancer:
    ingress:
    - ip: 10.0.0.80