# Create a Persistent Volume Claim

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: donationsdesk-pv-claim
  namespace: donationsdesk
spec:
  storageClassName: ""
  # Name of the volume to tie to this claim
  volumeName: donationsdesk-pv
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem  
  resources:
    requests:
      storage: 1Gi